# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pederiodo_avaliacao', models.IntegerField()),
                ('dias_mais_quatro', models.IntegerField()),
                ('media_horas', models.FloatField()),
                ('pressao_media', models.FloatField()),
                ('iah', models.FloatField()),
                ('ia', models.FloatField()),
                ('ih', models.FloatField()),
                ('ia_central', models.FloatField()),
                ('queixa', models.CharField(max_length=500)),
                ('conduta', models.CharField(max_length=500)),
                ('valor_consulta', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='doenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('peso', models.FloatField(verbose_name=10)),
                ('altura', models.FloatField(verbose_name=10)),
                ('observacao', models.CharField(max_length=500)),
                ('queixa', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='retorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
    ]
