# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confisioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='altura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.FloatField(),
        ),
    ]
