# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confisioapp', '0002_auto_20170913_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='\\img\\chaifoto.jpg'),
        ),
    ]
