# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confisioapp', '0005_paciente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='id_paciente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='confisioapp.Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='doenca_paciente',
            field=models.ManyToManyField(to='confisioapp.Doenca'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='equipamento_paciente',
            field=models.ManyToManyField(to='confisioapp.Equipamento'),
        ),
        migrations.AddField(
            model_name='retorno',
            name='id_paciente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='confisioapp.Paciente'),
            preserve_default=False,
        ),
    ]
