# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confisioapp', '0006_auto_20171018_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='doenca_paciente',
            new_name='doenca',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='equipamento_paciente',
            new_name='equipamento',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='doenca',
            field=models.ManyToManyField(to='confisioapp.Doenca'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='equipamento',
            field=models.ManyToManyField(to='confisioapp.Equipamento'),
        ),
    ]
