# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confisioapp', '0007_auto_20171019_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='doenca',
            field=models.ManyToManyField(to='confisioapp.Doenca'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='equipamento',
            field=models.ManyToManyField(to='confisioapp.Equipamento'),
        ),
    ]
