# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confisioapp', '0009_auto_20171019_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='doenca',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='queixa',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='doenca',
            field=models.ManyToManyField(to='confisioapp.Doenca'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='equipamento',
            field=models.ManyToManyField(to='confisioapp.Equipamento'),
        ),
    ]
